<a target="_blank" href="https://colab.research.google.com/github/sonder-art/fdd_p25/blob/main/professor/numpy/notebooks/04_Operaciones_Basicas_y_Broadcasting.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


# 04 — Operaciones básicas y Broadcasting

- Aritmética elemento a elemento
- Comparaciones
- Producto matricial `@`
- Broadcasting en operaciones



In [ ]:
import numpy as np

x = np.array([-1,0,1,2])
(x*2, x**2, x+2, -x)
#una lista no sabe que trae, pero numpy si lo sabe 


(array([-2,  0,  2,  4]),
 array([1, 0, 1, 4]),
 array([1, 2, 3, 4]),
 array([ 1,  0, -1, -2]))

In [ ]:
# Comparaciones y where
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
np.where(a == b)
#a == b 
# donde los valores de a son iguales a los de b en la misma posición <- nos regresa una mask 


(array([0, 3, 4]),)

In [ ]:
# Producto matricial
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[2,3,4],[5,6,7],[8,9,10]])
A @ B #esto es lo que hace la multiplicación matricial (renglón por columna)


In [ ]:
# Broadcasting
#solo funciona si la primera dimensión cuadra, sino truena 

v = np.arange(3) #del 0 al 2
M = np.ones((3,3)) #matriz de 3x3
M + v #Dimensión -> (3, nada)


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])